# debian testing extras
FROM lukasnellen/sysdev:d-testing

LABEL maintainers="Lukas Nellen <lukas@nucleares.unam.mx>" \
      name="Software install environment - debian testing extended" 

RUN apt-get update && \
    apt-get install --no-install-recommends --yes \ 
    clang \
    clang-5.0 \
    clang-6.0 \
    gcc-8 \
    g++-8 \
    gfortran-8 \
    gcc-6 \
    g++-6 \
    gfortran-6 \
  && \
# cleanup
    apt-get clean && rm -rf /var/lib/apt/lists/*
