# debian testing extras
FROM lukasnellen/sysdev:d-testing

LABEL maintainers="Lukas Nellen <lukas@nucleares.unam.mx>" \
      name="Software install environment - debian testing extended" 

RUN apt-get update && \
    apt-get install --no-install-recommends --yes \ 
    clang \
    clang-6.0 \
    gcc-7 \
    g++-7 \
    gfortran-7 \
  && \
# cleanup
    apt-get clean && rm -rf /var/lib/apt/lists/*
