#! /bin/bash
#
# Build arch system image for ape installations
#

docker_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

docker build -t lukasnellen/sysdev:a-latest \
       --pull \
       ${docker_dir}
